on: [push, pull_request]

name: CI

jobs:
  ci:
    name: Compile and Test
    runs-on: macos-latest
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm/10.0
          key: ${{ runner.os }}-cached-llvm-10.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '10.0'
          directory: ${{ runner.temp }}/llvm/10.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: false

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ steps.rust_toolchain.outputs.rustc_hash }}

      - name: Install Cargo Tools (cargo-make)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cargo-make

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v2
        with:
          path: /Users/runner/android/ndk-bundle
          key: ${{ runner.os }}-cached-ndk

      - name: Install Android NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: $ANDROID_SDK_ROOT/tools/bin/sdkmanager ndk-bundle

      - name: Set Android NDK Env
        run: echo "ANDROID_NDK_HOME=/Users/runner/android/ndk-bundle" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Install Android Targets
        run: rustup target add aarch64-linux-android x86_64-linux-android

      - name: Install iOS Targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Run cargo make native (Debug)
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: native

      - name: Run cargo make android-dev (Debug)
        if: ${{ false }} # disable android
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: android-dev

      - name: Run cargo make ios (Debug)
        if: ${{ false }} # disable ios
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: ios

      - name: Run flutter test
        run: flutter test


